name: flutter_native_image
description: A new flutter plugin project.
version: 0.0.1
author: btastic
homepage: https://github.com/btastic

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutternativeimage
    pluginClass: FlutterNativeImagePlugin